# Generated by Django 2.2 on 2019-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('ShopId', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('ShopName', models.CharField(max_length=50)),
                ('LastGotTime', models.FloatField(default=0)),
                ('LastCheckTime', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TryActivity',
            fields=[
                ('ActivityId', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('TrialSkuId', models.IntegerField()),
                ('StartTime', models.FloatField()),
                ('EndTime', models.FloatField()),
                ('SupplyCount', models.IntegerField()),
                ('TrialName', models.CharField(max_length=200)),
                ('ShopName', models.CharField(default='', max_length=50)),
                ('ShopId', models.IntegerField(default=0)),
                ('Price', models.FloatField()),
                ('UpdateTime', models.FloatField(default=1557067246.8553293)),
            ],
        ),
    ]
